version: "3.9"

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /Users/axel/Desktop/grouppeo_sncf/client:/app

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /Users/axel/Desktop/grouppeo_sncf/api:/app
